// Generated by Google Gemini
import { Client } from "pg";
import path from "path";
import { fileURLToPath } from "url";
import { config } from "./schema-generator-config";
import { fetchDbSchemas } from "./schema-db-fetcher";
import {
  prepareOutputDir,
  writeSchemasToFile,
  writeFunctionSchemasToFile,
} from "./schema-file-writer";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  const client = new Client(config.db);
  try {
    await client.connect();

    const { tables, views, functions } = await fetchDbSchemas(
      client,
      config.schema
    );

    const outputDir = path.resolve(__dirname, config.outputDir);
    const tablesDir = path.join(outputDir, "tables");
    const viewsDir = path.join(outputDir, "views");

    prepareOutputDir(outputDir, ["tables", "views"]);

    console.log("✅ Generiere Zod-Schemas für Tabellen...");
    writeSchemasToFile(tables, tablesDir);

    console.log("\n✅ Generiere Zod-Schemas für Views...");
    writeSchemasToFile(views, viewsDir);

    console.log("\n✅ Generiere Zod-Schemas für Funktions-Parameter...");
    writeFunctionSchemasToFile(functions, outputDir);

    console.log("\n🏁 Alle Schemas erfolgreich erstellt.");
  } catch (err) {
    console.error("❌ Fehler beim Generieren:", err);
  } finally {
    await client.end();
  }
}

main();
