CREATE TABLE IF NOT EXISTS "public"."product_types" (
    "id" bigint generated by DEFAULT AS identity NOT NULL,
    "created_at" timestamp WITH time zone DEFAULT "now"() NOT NULL,
    "display_name" "text" NOT NULL,
    "emoji" "text" NOT NULL,
    CONSTRAINT product_types_pkey PRIMARY KEY (id),
    CONSTRAINT product_types_display_name_key UNIQUE (display_name)
);

ALTER TABLE public.product_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Deny read access for anon" ON public.product_types AS PERMISSIVE FOR
SELECT TO anon USING (false);

CREATE POLICY "Allow read access for authenticated users" ON public.product_types AS PERMISSIVE FOR
SELECT TO authenticated USING (TRUE);

ALTER TABLE "public"."products"
ADD COLUMN "fk_product_type" smallint NOT NULL DEFAULT '1'::smallint;

ALTER TABLE "public"."products"
ALTER COLUMN "fk_product_type" DROP DEFAULT;